# This project config must be located in: %project_root%/.rusty_dev_tool/config.toml

# Mandatory field
local_key = "rdt"
# Just using at for aliases
no_docker_compose = true

# Mandatory node
[commands]
# All commands must have a command and an alias but are optional in general
    [commands.build]
        "alias" = "build"
        "command" = "cargo build --release && cp target/release/rusty_dev_tool /usr/local/bin/rdt && ls -lah /usr/local/bin/rdt && echo \"\\033[32mBuilt and copied!\\033[39m\""
    [commands.clippy]
        "alias" = "clippy"
        "command" = "cargo clippy -- -D clippy::all -D warnings -D clippy::pedantic -D clippy::nursery"
    [commands.test]
        "alias" = "test"
        "command" = "cargo test"

# Mandatory node
[environments]
