# This project config must be located in: %project_root%/.rusty_dev_tool/config.toml

# Mandatory field
local_key = "rdt"
# Just using it for aliases
no_docker_compose = true

# Mandatory node
[commands]
# All commands must have a command and an alias but are optional in general
    [commands.build]
        "alias" = "build"
        # This is being used on macOS to easy and fast build during coding
        "command" = "cargo build --release && cp target/release/rusty_dev_tool /usr/local/bin/rdt && ls -lah /usr/local/bin/rdt && echo \"\\033[32mBuilt and copied!\\033[39m\""
    [commands.clippy]
        "alias" = "clippy"
        "command" = "cargo clippy -- -D clippy::all -D warnings -D clippy::pedantic -D clippy::nursery"
    [commands.test]
        "alias" = "test"
        "command" = "cargo test"
    [commands.test-coverage]
        "alias" = "test-coverage"
        "command" = "RUSTFLAGS=\"-C instrument-coverage\" LLVM_PROFILE_FILE=\"rusty_dev_tool-%p-%m.profraw\" cargo clean && RUSTFLAGS=\"-C instrument-coverage\" LLVM_PROFILE_FILE=\"rusty_dev_tool-%p-%m.profraw\" cargo test && grcov . --binary-path ./target/debug/ -s . -t html --ignore-not-existing --excl-start \"#\\[cfg\\(test\\)\\]\" --excl-line \"#\\[derive\\(\" --ignore \"/*\" -o ./target/debug/coverage/ && rm rusty_dev_tool*.profraw"
    [commands.generate-completions]
        # Updating our completions script
        "alias" = "generate-completions"
        "command" = "rdt --generate-completions > ~/.zsh/completions_script.sh && source ~/.zsh/completions_script.sh"

# Mandatory node
[environments]
