# This home config must be located in: %home_dir%/.rusty_dev_tool/config.toml

# Mandatory
rdt_name = "rdt"

# Mandatory but can be changed to pull custom forked or private hosted versions.
download_path = "https://github.com/BentBr/rusty_dev_tool/releases/download"
meta_path = "https://api.github.com/repos/BentBr/rusty_dev_tool/releases/latest"

# Mandatory node
[commands]
    # Each command is optional
    [commands.alpha]
        # Command to be executed is mandatory
        command = "ls -lah"
        # As is its alias
        alias = "lisa"

    # Each command it optional
    [commands.another_name]
        command = "chown -R www-data:www-data /path/to/folder"
        alias = "porn"

    [commands.stan]
        # Global stan example
        command = "docker-compose exec -T php vendor/bin/phpstan analyse -c phpstan.neon"
        alias = "stan-d"

    [commands.stan-m]
        # Global stan example
        command = "mutagen-compose exec -T php vendor/bin/phpstan analyse -c phpstan.neon"
        alias = "stan-md"