# This project config must be located in: %project_root%/.rusty_dev_tool/config.toml

# Mandatory field
local_key = "abc"
no_docker_compose = false

# Mandatory node
[commands]
    # All commands must have a command and an alias but are optional in general
    [commands.first]
        command = "command1"
        alias = "alias1"

    [commands.second]
        command = "command2"
        alias = "alias2"

# Mandatory node
[environments]
    # All environments must have a name and a uri but are optional in general
    [environments.dev]
        name = "environment1"
        uri = "uri1"

    [environments.prod]
        name = "environment2"
        uri = "uri2"
