# This project config must be located in: %project_root%/.rusty_dev_tool/config.toml

# Mandatory field
local_key = "abc"
# If you want to use docker compose, set this to true. So you can use the custom commands and everything not related
# to docker compose will be ignored (or fail gracefully)
no_docker_compose = false

# Mandatory node
[commands]
    # All commands must have a command and an alias but are optional in general
    [commands.first]
        execution = "command1"
        alias = "alias1"
        description = "description1"

    [commands.second]
        execution = "command2"
        alias = "alias2"
        description = "description2"

# Mandatory node
[environments]
    # All environments must have a name and a uri but are optional in general
    [environments.dev]
        name = "environment1"
        uri = "uri1"

    [environments.prod]
        name = "environment2"
        uri = "uri2"
