name: Clippy

on: [ push, pull_request ]

jobs:
    clippy:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Run Clippy
                uses: actions-rs/clippy-check@v1
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    args: --all-targets -- -D warnings