name: release-please

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Run release-please
                id: release
                uses: GoogleCloudPlatform/release-please-action@v2
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    release-type: rust
                    package-name: "rusty_dev_tool"

            - name: Debug release-please outputs
              run: |
                  echo "Release created: ${{ steps.release.outputs.release_created }}"
                  echo "Release tag: ${{ steps.release.outputs.release_tag }}"
                  echo "Release tag: Somethihg else"
                  
            -   name: Trigger release workflow
                if: ${{ steps.release.outputs.release_created }}
                uses: benc-uk/workflow-dispatch@v1
                with:
                    workflow: release
                    token: ${{ secrets.GITHUB_TOKEN }}
                    inputs: '{"tag_name": "${{ steps.release.outputs.release_tag }}"}'